In [1]:
from IPython.display import clear_output
from Buy_Presure_Scaner import *
from Volatile_4h_Scaner import *
from Gainer_List import *
from Consolidation_24_Scaner import *
from RSI_30_Scaner import *
from Fetch_Live_Data import *
from Chandelier_ZLSMA import *
from Trade_Execution import *
from Trade_Selection import *
from Trade_Selection_All import *

In [39]:
scalping_filter = BinanceAllUSDTScalpingFilter(
    max_workers=8,
    delay_between_requests=0.1,
    weight_profile='volatile'  # Options: 'balanced', 'volatile', 'trending'
)

print("Scanning ALL Binance USDT pairs for scalping opportunities...")

best_coins = scalping_filter.filter_all_usdt_pairs(
    min_volume=50_000,
    top_n=30,
    use_parallel=True,
    volume_filter_first=False,
    use_percentile_volume=True  # NEW: Use percentile-based volume filter
)

best_coins =pd.DataFrame(best_coins)

"""high_volume_coins = scalping_filter.filter_all_usdt_pairs(
    min_volume=1_000_000,
    top_n=20,
    use_parallel=True,
    volume_filter_first=True,
    use_percentile_volume=False
)
high_volume_coins =pd.DataFrame(high_volume_coins)"""

Scanning ALL Binance USDT pairs for scalping opportunities...
Found 399 total USDT trading pairs

'high_volume_coins = scalping_filter.filter_all_usdt_pairs(\n    min_volume=1_000_000,\n    top_n=20,\n    use_parallel=True,\n    volume_filter_first=True,\n    use_percentile_volume=False\n)\nhigh_volume_coins =pd.DataFrame(high_volume_coins)'

In [42]:
best_coins = best_coins[(best_coins['trend_direction']==1) & (best_coins['rsi'] <= 60) & (best_coins['current_price'] <= 20)]
#high_volume_coins = high_volume_coins[(high_volume_coins['trend_direction']==1) & (high_volume_coins['rsi'] <= 70) & (high_volume_coins['current_price'] <= 20)]

In [43]:
best_coins

,symbol,current_price,volume_24h,price_change_24h,rsi,atr,volatility,volume_trend,buy_pressure,price_momentum,spread_pct,trade_count,weighted_avg_price,price_range_24h,trend_direction,trend_strength,scalping_score
3,XRPUSDT,2.137900,3.671054e+08,-4.702,59.827586,1.245714e-02,4.402503,1.073935,0.531058,1.087522,0.004677,1572783,2.157400,8.282120,1,0,70.6
7,DOGEUSDT,0.174580,2.790952e+08,-8.043,59.846827,1.137143e-03,5.620247,1.258855,0.534860,0.854997,0.005728,1424142,0.178756,12.026844,1,0,68.3
8,SHIBUSDT,0.000012,5.181959e+07,-7.981,53.731343,8.500000e-08,5.590236,1.452997,0.525813,0.512821,0.085034,758836,0.000012,12.565905,1,0,68.3
9,ADAUSDT,0.635800,1.221785e+08,-7.236,54.947917,4.321429e-03,5.692617,1.128111,0.542610,0.936657,0.015728,440493,0.648539,11.775186,1,0,68.1
16,LINKUSDT,13.230000,9.699724e+07,-8.380,51.648352,1.064286e-01,6.313769,1.133604,0.519018,0.227273,0.075643,275265,13.605789,14.352941,1,0,61.1
18,DOTUSDT,3.816000,3.444834e+07,-6.013,56.398104,2.678571e-02,5.125470,1.196207,0.595209,1.032566,0.026219,130986,3.860560,12.036026,1,0,60.3
19,ETCUSDT,16.380000,1.699561e+07,-7.874,56.790123,9.500000e-02,5.228464,0.925771,0.528986,0.800000,0.061050,114495,16.769006,11.521603,1,0,60.1
24,JSTUSDT,0.032670,3.479061e+06,-2.941,59.090909,8.714286e-05,2.839581,0.438765,0.645071,0.895615,0.030609,13928,0.032769,6.332288,1,0,58.6

In [ ]:
stablecoins = {
    'GUSDUSDT','FRAXUSDT','USDDUSDT','MIMUSDT','LUSDUSDT',
    'FDUSDUSDT','FEIUSDT','HUSDUSDT','SUSDUSDT','OUSDUSDT',
    'USTCUSDT','VAIUSDT','DOLAUSDT','ALUSDUSDT','MUSDUSDT',
    'DUSDUSDT','CUSDUSDT','USDCUSDT','NUSDUSDT','ZUSDUSDT','EURUSDT','XUSDUSDT'
}

df = get_binance_buy_presure(min_volume_usdt=1_000_000, top_n=50)

# remove any rows whose symbol is in the stablecoins set
df_filtered = df[~df['symbol'].isin(stablecoins)]

In [22]:
df_filtered

,rank,symbol,current_buy_pressure,current_sell_pressure,avg_buy_pressure_5periods,buy_pressure_trend,latest_price_change,latest_volume,volume_trend,volatility,timestamp,signal,momentum
1,2,OPUSDT,53.50,46.50,56.53,-1.97,0.00,4.825158e+05,-14.03,1.81,2025-06-13T18:09:08.729344,AVOID,BUILDING
2,3,BTCUSDT,50.33,49.67,56.44,2.43,0.02,1.010635e+02,-0.82,0.54,2025-06-13T18:09:08.561578,WATCH,STRONG
4,5,AUSDT,59.00,41.00,55.96,0.23,0.08,6.831750e+04,-27.10,1.39,2025-06-13T18:09:08.932077,AVOID,BUILDING
5,6,SOLVUSDT,64.59,35.41,55.87,0.63,0.13,8.743240e+05,7.81,1.68,2025-06-13T18:09:09.478737,BUY,STRONG
6,7,BOMEUSDT,59.91,40.09,55.83,1.81,0.32,3.195251e+07,-11.16,1.40,2025-06-13T18:09:09.238878,AVOID,GOOD
7,8,TONUSDT,57.19,42.81,55.81,0.03,-0.03,9.231056e+04,1.90,0.78,2025-06-13T18:09:08.824605,WATCH,BUILDING
8,9,ENSUSDT,69.73,30.27,55.55,4.96,0.25,5.612360e+03,-2.78,1.25,2025-06-13T18:09:09.005724,WATCH,STRONG
9,10,ETCUSDT,75.82,24.18,55.33,11.14,0.12,4.554170e+03,-10.84,0.93,2025-06-13T18:09:09.027946,AVOID,STRONG
10,11,TRXUSDT,82.83,17.17,55.31,9.75,0.11,3.804087e+06,-1.71,0.37,2025-06-13T18:09:08.579814,WATCH,STRONG
11,12,AVAXUSDT,56.30,43.70,55.13,2.11,0.36,1.997618e+04,4.82,1.14,2025-06-13T18:09:08.688010,BUY,STRONG
12,13,PENDLEUSDT,48.99,51.01,55.03,-2.07,-0.27,1.125310e+04,-27.13,2.29,2025-06-13T18:09:08.830251,AVOID,BUILDING
13,14,LINKUSDT,61.15,38.85,54.97,3.48,0.15,1.798523e+04,-13.28,1.23,2025-06-13T18:09:08.679502,AVOID,STRONG
14,15,FETUSDT,63.33,36.67,54.54,2.96,0.45,2.453791e+05,-3.86,1.49,2025-06-13T18:09:08.760911,WATCH,STRONG
15,16,XLMUSDT,62.35,37.65,54.50,1.61,0.15,2.672460e+05,-6.70,0.77,2025-06-13T18:09:08.902429,WATCH,GOOD
16,17,PEPEUSDT,48.61,51.39,54.19,-2.73,0.28,1.381980e+11,-7.27,1.38,2025-06-13T18:09:08.611877,AVOID,BUILDING
17,18,LTCUSDT,52.96,47.04,54.16,2.27,0.12,1.397408e+03,-25.13,0.92,2025-06-13T18:09:08.734754,AVOID,STRONG
18,19,SHIBUSDT,46.43,53.57,54.12,-0.71,0.17,1.216456e+10,32.70,1.07,2025-06-13T18:09:08.748367,AVOID,STRONG
19,20,ARBUSDT,48.01,51.99,54.09,-4.16,0.38,8.891393e+05,5.57,1.23,2025-06-13T18:09:08.752233,AVOID,GOOD
20,21,RVNUSDT,61.68,38.32,53.71,3.12,1.92,1.371817e+07,5.70,2.70,2025-06-13T18:09:08.941928,WATCH,EXPLOSIVE
21,22,KAITOUSDT,66.29,33.71,53.62,4.61,-0.16,2.852770e+04,-1.92,1.59,2025-06-13T18:09:09.022320,WATCH,GOOD
22,23,PEOPLEUSDT,52.67,47.33,53.10,-1.54,0.39,1.603636e+06,-14.34,1.55,2025-06-13T18:09:09.467373,AVOID,BUILDING
23,24,XRPUSDT,44.79,55.21,53.08,-2.51,0.22,6.616915e+05,1.10,0.96,2025-06-13T18:09:08.584171,AVOID,GOOD
24,25,INITUSDT,51.89,48.11,53.00,0.55,-0.29,3.927557e+05,-0.70,2.23,2025-06-13T18:09:08.880027,WATCH,BUILDING
25,26,AAVEUSDT,52.06,47.94,52.82,0.09,0.01,2.195209e+03,-1.64,2.36,2025-06-13T18:09:08.637865,WATCH,BUILDING
26,27,DYDXUSDT,76.37,23.63,52.80,9.06,0.08,1.015911e+05,-9.41,1.11,2025-06-13T18:09:09.182019,AVOID,STRONG
27,28,LDOUSDT,62.29,37.71,52.73,0.54,0.12,5.326995e+04,7.51,1.57,2025-06-13T18:09:08.907551,WATCH,STRONG
28,29,HMSTRUSDT,50.48,49.52,52.68,2.34,-0.22,1.425226e+08,-24.60,1.90,2025-06-13T18:09:09.127818,AVOID,GOOD
29,30,GALAUSDT,55.57,44.43,52.58,0.54,0.27,2.546410e+06,-11.46,1.15,2025-06-13T18:09:08.946344,AVOID,GOOD
30,31,POLUSDT,57.02,42.98,52.43,4.00,0.45,2.208404e+05,-1.25,1.10,2025-06-13T18:09:09.000961,WATCH,STRONG
31,32,TSTUSDT,52.40,47.60,52.39,1.31,0.26,1.728760e+06,-15.24,2.46,2025-06-13T18:09:09.081250,AVOID,GOOD
32,33,PENGUUSDT,59.74,40.26,52.30,2.61,0.16,2.040398e+07,-10.45,1.42,2025-06-13T18:09:08.893738,AVOID,STRONG
33,34,APTUSDT,51.83,48.17,52.18,-0.87,0.20,3.843272e+04,55.97,1.30,2025-06-13T18:09:08.897864,AVOID,STRONG
34,35,RENDERUSDT,51.98,48.02,52.02,1.46,0.32,1.715506e+04,2.00,1.21,2025-06-13T18:09:08.885478,WATCH,STRONG
35,36,ETHFIUSDT,52.64,47.36,51.91,-1.09,0.28,1.095124e+05,11.48,1.69,2025-06-13T18:09:08.743401,AVOID,GOOD
36,37,SUIUSDT,42.56,57.44,51.81,-3.43,0.04,4.268803e+05,-38.86,1.54,2025-06-13T18:09:08.602880,AVOID,BUILDING
37,38,AXLUSDT,62.29,37.71,51.56,3.95,0.07,4.960841e+04,-41.78,1.35,2025-06-13T18:09:09.197337,AVOID,STRONG
38,39,SOLUSDT,44.06,55.94,51.55,-1.09,0.09,2.536479e+04,-12.17,0.99,2025-06-13T18:09:08.595058,AVOID,BUILDING
39,40,XUSDUSDT,7.34,92.66,51.36,1.74,0.00,6.096800e+04,242.18,0.02,2025-06-13T18:09:08.969026,WATCH,EXPLOSIVE
40,41,NEARUSDT,47.57,52.43,51.23,-1.21,0.13,5.235630e+04,-1.63,1.26,2025-06-13T18:09:08.780653,AVOID,BUILDING
41,42,ICPUSDT,60.10,39.90,51.21,2.97,0.07,1.473679e+04,6.79,1.18,2025-06-13T18:09:08.961130,WATCH,EXPLOSIVE
42,43,ENAUSDT,55.64,44.36,51.17,2.39,0.30,9.561316e+05,1.25,1.81,2025-06-13T18:09:08.661349,WATCH,STRONG
43,44,ARKMUSDT,40.44,59.56,51.17,-0.10,0.00,1.108433e+05,-17.71,1.48,2025-06-13T18:09:09.171629,AVOID,BUILDING
44,45,AIXBTUSDT,52.56,47.44,51.03,1.14,1.27,7.300217e+06,29.29,2.54,2025-06-13T18:09:08.861521,WATCH,EXPLOSIVE
45,46,DOGEUSDT,47.65,52.35,51.02,-2.42,0.16,5.234966e+06,10.08,0.95,2025-06-13T18:09:08.607270,AVOID,GOOD
46,47,BCHUSDT,29.41,70.59,51.02,-8.06,0.14,3.943720e+02,-23.37,2.13,2025-06-13T18:09:08.876173,AVOID,BUILDING
47,48,TRBUSDT,38.48,61.52,50.66,-4.64,-0.44,7.474760e+02,-19.19,1.74,2025-06-13T18:09:09.017973,AVOID,BUILDING
48,49,TIAUSDT,55.12,44.88,50.48,1.19,0.39,3.071525e+04,-15.16,1.16,2025-06-13T18:09:08.817228,AVOID,GOOD
49,50,ETHUSDT,47.79,52.21,50.33,-0.40,0.21,2.833372e+03,1.36,0.98,2025-06-13T18:09:08.619609,AVOID,GOOD

In [25]:
df_filtered.nlargest(5, 'volume_trend')

,rank,symbol,current_buy_pressure,current_sell_pressure,avg_buy_pressure_5periods,buy_pressure_trend,latest_price_change,latest_volume,volume_trend,volatility,timestamp,signal,momentum
39,40,XUSDUSDT,7.34,92.66,51.36,1.74,0.00,6.096800e+04,242.18,0.02,2025-06-13T18:09:08.969026,WATCH,EXPLOSIVE
33,34,APTUSDT,51.83,48.17,52.18,-0.87,0.20,3.843272e+04,55.97,1.30,2025-06-13T18:09:08.897864,AVOID,STRONG
18,19,SHIBUSDT,46.43,53.57,54.12,-0.71,0.17,1.216456e+10,32.70,1.07,2025-06-13T18:09:08.748367,AVOID,STRONG
44,45,AIXBTUSDT,52.56,47.44,51.03,1.14,1.27,7.300217e+06,29.29,2.54,2025-06-13T18:09:08.861521,WATCH,EXPLOSIVE
35,36,ETHFIUSDT,52.64,47.36,51.91,-1.09,0.28,1.095124e+05,11.48,1.69,2025-06-13T18:09:08.743401,AVOID,GOOD

In [2]:
symbols = "APTUSDT"

In [6]:
# Define your function to fetch, calculate, and merge the data
def fetch_and_process_data(symbol):
    df = get_single_fetch(symbol, 500)  # Fetch data
    df_zlsma = calculate_zlsma(df, close_column='close', length=200)  # Calculate ZLSMA
    df_chandelier = calculate_chandelier(df, atr_period=1, atr_multiplier=2.0)  # Calculate Chandelier
    merged_chandelier_zlsma = merge_zlsma_chandelier(df_zlsma, df_chandelier)  # Merge ZLSMA and Chandelier
    merged_chandelier_zlsma = merged_chandelier_zlsma[["timestamp", "close", "zlsma_200", "buy_signal", "sell_signal"]]  # Filter relevant columns
    return merged_chandelier_zlsma[490:]

"""def run_task():
    # Get the latest symbols every 2 hours
    symbols = get_max_buy_pressure_trend_symbols()
    return symbols"""

def fetch_and_display_data_(symbols):
    # Run the fetch_and_process_data every 10 seconds to display results
    result = fetch_and_process_data(symbols)
    clear_output(wait=True)  # Clear previous output in Jupyter Notebook
    print("Monitoring on: ", symbols)
    print(result)  # Display the new result
    print("\n")
    
    return result

# Main loop that runs every 2 hours
"""while True:
    symbols = run_task()  # Get the symbols every 2 hours
    print("New symbols received. Monitoring begins...\n")"""
    
# Continuous 10-second updates with fetched data
while True:
    out = fetch_and_display_data_(symbols)

    # Check if the DataFrame is not empty and get the last row
    if not out.empty:
        # Access the last row using iloc[-1]
        if out['close'].iloc[-1] > out['zlsma_200'].iloc[-1] and out['buy_signal'].iloc[-1] == True:
            print("Buy signal detected for symbols:", symbols)
        else:
            print("No buy signal detected for symbols:", symbols)
    else:
        print("The DataFrame is empty. No data available.")
    
    time.sleep(10)  # Wait for 10 seconds before running the next iteration

Monitoring on:  APTUSDT
              timestamp  close  zlsma_200  buy_signal  sell_signal
490 2025-06-13 15:45:00  4.443   4.364083           1            0
491 2025-06-13 16:00:00  4.429   4.356402           1            0
492 2025-06-13 16:15:00  4.440   4.349775           1            0
493 2025-06-13 16:30:00  4.448   4.343659           1            0
494 2025-06-13 16:45:00  4.449   4.337751           1            0
495 2025-06-13 17:00:00  4.523   4.335407           1            0
496 2025-06-13 17:15:00  4.473   4.331148           1            0
497 2025-06-13 17:30:00  4.435   4.325480           1            0
498 2025-06-13 17:45:00  4.434   4.320295           1            0
499 2025-06-13 18:00:00  4.433   4.315609           1            0


Buy signal detected for symbols: APTUSDT

KeyboardInterrupt: